packages:
  - backend
  - frontend
onlyBuiltDependencies:
  - '@prisma/client'
  - '@prisma/engines'
  - bcrypt
  - esbuild
  - prisma
allowBuilds:
  '@prisma/client': true
  '@prisma/engines': true
  bcrypt: true
  esbuild: true
  prisma: true
