import { useState, type FormEvent } from 'react';
import { Trash2 } from 'lucide-react';
import { Modal } from './Modal'; import { api, getErrorMessage } from '../services/api'; import type { Project } from '../types';
export function ProjectForm({ project, onClose, onSaved }: { project?: Project; onClose: () => void; onSaved: (project: Project) => void }) {
  const [error, setError] = useState(''); const [busy, setBusy] = useState(false);
  async function submit(e: FormEvent<HTMLFormElement>) { e.preventDefault(); const values = new FormData(e.currentTarget); setBusy(true); setError(''); try { const body = { name: String(values.get('name')), description: String(values.get('description')) || null }; const response = project ? await api.patch(`/projects/${project.id}`, body) : await api.post('/projects', body); onSaved(response.data.project); onClose(); } catch (err) { setError(getErrorMessage(err)); } finally { setBusy(false); } }
  async function deleteProject() { if (!project || !window.confirm('Delete this project and all of its tasks permanently?')) return; setBusy(true); try { await api.delete(`/projects/${project.id}`); window.location.assign('/projects'); } catch (err) { setError(getErrorMessage(err)); setBusy(false); } }
  return <Modal title={project ? 'Edit project' : 'Create project'} onClose={onClose}><form onSubmit={submit} className="space-y-4"><label><span className="label">Project name</span><input name="name" required minLength={2} defaultValue={project?.name} placeholder="Website redesign"/></label><label><span className="label">Description <span className="font-normal text-slate-400">(optional)</span></span><textarea name="description" rows={4} defaultValue={project?.description ?? ''} placeholder="What is this project about?"/></label>{error && <p className="text-sm text-rose-600">{error}</p>}<div className="flex justify-between gap-3 border-t border-slate-100 pt-4">{project ? <button type="button" onClick={deleteProject} disabled={busy} className="btn text-rose-600 hover:bg-rose-50"><Trash2 size={16}/>Delete</button> : <span/>}<div className="flex gap-3"><button type="button" onClick={onClose} className="btn-secondary">Cancel</button><button disabled={busy} className="btn-primary">{busy ? 'Saving…' : project ? 'Save changes' : 'Create project'}</button></div></div></form></Modal>;
}
