import { DndContext, DragOverlay, PointerSensor, useDroppable, useSensor, useSensors, type DragEndEvent, type DragStartEvent } from '@dnd-kit/core';
import { SortableContext, verticalListSortingStrategy } from '@dnd-kit/sortable';
import { ArrowLeft, Edit3, Plus, Users } from 'lucide-react';
import { useCallback, useEffect, useState } from 'react';
import { Link, useParams } from 'react-router-dom';
import { Loading } from '../components/Loading'; import { TaskCard } from '../components/TaskCard'; import { TaskForm } from '../components/TaskForm'; import { MembersModal } from '../components/MembersModal'; import { ProjectForm } from '../components/ProjectForm';
import { api, getErrorMessage } from '../services/api'; import type { Project, Task, TaskStatus } from '../types'; import { useAuth } from '../contexts/AuthContext';

const columns: { status: TaskStatus; title: string; color: string }[] = [
  { status: 'TODO', title: 'Todo', color: 'bg-slate-400' }, { status: 'IN_PROGRESS', title: 'In Progress', color: 'bg-blue-500' },
  { status: 'REVIEW', title: 'Review', color: 'bg-amber-500' }, { status: 'DONE', title: 'Done', color: 'bg-emerald-500' },
];
function Column({ status, title, color, tasks, onCreate, onSelect }: { status: TaskStatus; title: string; color: string; tasks: Task[]; onCreate: () => void; onSelect: (task: Task) => void }) {
  const { setNodeRef, isOver } = useDroppable({ id: status });
  return <section ref={setNodeRef} className={`min-h-48 rounded-xl bg-slate-100/80 p-3 ${isOver ? 'ring-2 ring-indigo-300' : ''}`}><header className="mb-3 flex items-center justify-between"><div className="flex items-center gap-2"><span className={`h-2 w-2 rounded-full ${color}`}/><h3 className="text-sm font-semibold text-ink">{title}</h3><span className="rounded bg-white px-1.5 py-0.5 text-xs text-slate-500">{tasks.length}</span></div><button onClick={onCreate} className="rounded p-1 text-slate-400 hover:bg-white hover:text-indigo-600" aria-label={`Add task to ${title}`}><Plus size={16}/></button></header><SortableContext items={tasks.map(t => t.id)} strategy={verticalListSortingStrategy}><div className="space-y-2">{tasks.map(task => <TaskCard key={task.id} task={task} onClick={() => onSelect(task)}/>)}</div></SortableContext></section>;
}
export function ProjectDetailPage() {
  const { projectId = '' } = useParams(); const { user } = useAuth(); const [project, setProject] = useState<Project>(); const [error, setError] = useState(''); const [activeTask, setActiveTask] = useState<Task>(); const [selectedTask, setSelectedTask] = useState<Task>(); const [createStatus, setCreateStatus] = useState<TaskStatus>(); const [membersOpen, setMembersOpen] = useState(false); const [editOpen, setEditOpen] = useState(false);
  const load = useCallback(() => { api.get(`/projects/${projectId}`).then(r => setProject(r.data.project)).catch(e => setError(getErrorMessage(e))); }, [projectId]);
  useEffect(() => { load(); }, [load]); const sensors = useSensors(useSensor(PointerSensor, { activationConstraint: { distance: 6 } })); const findTask = (id: string) => project?.tasks?.find(t => t.id === id);
  async function onDragEnd(event: DragEndEvent) {
    setActiveTask(undefined); const task = findTask(String(event.active.id)); if (!task || !event.over) return; const destination = String(event.over.id); const target = findTask(destination); const status = target?.status ?? (columns.some(c => c.status === destination) ? destination as TaskStatus : task.status); if (status === task.status && destination === task.id) return;
    const siblings = project?.tasks?.filter(t => t.status === status && t.id !== task.id) ?? []; const position = target ? siblings.findIndex(t => t.id === target.id) : siblings.length;
    try { const r = await api.patch(`/tasks/${task.id}/move`, { status, position: Math.max(position, 0) }); setProject(current => current ? { ...current, tasks: current.tasks?.map(t => t.id === task.id ? r.data.task : t).sort((a, b) => a.status.localeCompare(b.status) || a.position - b.position) } : current); } catch (e) { setError(getErrorMessage(e)); load(); }
  }
  if (error && !project) return <p className="text-rose-600">{error}</p>; if (!project) return <Loading/>; const currentMembership = project.members?.find(m => m.user.id === user?.id); const canManage = currentMembership?.role === 'ADMIN'; const tasks = project.tasks ?? [];
  return <><Link to="/projects" className="mb-5 inline-flex items-center gap-1 text-sm font-medium text-slate-500 hover:text-indigo-600"><ArrowLeft size={16}/>Projects</Link><header className="mb-7 flex flex-wrap items-start justify-between gap-4"><div><div className="flex items-center gap-2"><h1 className="text-2xl font-semibold text-ink">{project.name}</h1>{canManage && <button onClick={() => setEditOpen(true)} className="rounded p-1 text-slate-400 hover:bg-slate-100"><Edit3 size={16}/></button>}</div><p className="mt-1 max-w-2xl text-sm text-slate-500">{project.description || 'No project description.'}</p></div><div className="flex gap-2"><button onClick={() => setMembersOpen(true)} className="btn-secondary"><Users size={16}/>Members ({project.members?.length ?? 0})</button><button onClick={() => setCreateStatus('TODO')} className="btn-primary"><Plus size={17}/>Add task</button></div></header>{error && <p className="mb-3 text-sm text-rose-600">{error}</p>}<DndContext sensors={sensors} onDragStart={(e: DragStartEvent) => setActiveTask(findTask(String(e.active.id)))} onDragEnd={onDragEnd} onDragCancel={() => setActiveTask(undefined)}><div className="grid gap-4 lg:grid-cols-4">{columns.map(c => <Column key={c.status} {...c} tasks={tasks.filter(t => t.status === c.status).sort((a, b) => a.position - b.position)} onCreate={() => setCreateStatus(c.status)} onSelect={setSelectedTask}/>)}</div><DragOverlay>{activeTask && <div className="w-64"><TaskCard task={activeTask} onClick={() => undefined}/></div>}</DragOverlay></DndContext>{createStatus && <TaskForm projectId={project.id} members={project.members ?? []} initialStatus={createStatus} onClose={() => setCreateStatus(undefined)} onSaved={() => load()}/>} {selectedTask && <TaskForm projectId={project.id} members={project.members ?? []} task={selectedTask} onClose={() => setSelectedTask(undefined)} onSaved={() => { setSelectedTask(undefined); load(); }} onDeleted={() => load()}/>} {membersOpen && <MembersModal projectId={project.id} members={project.members ?? []} canManage={canManage} currentUserId={user?.id} onClose={() => setMembersOpen(false)} onUpdated={load}/>} {editOpen && <ProjectForm project={project} onClose={() => setEditOpen(false)} onSaved={updated => { setProject(updated); setEditOpen(false); }}/>}</>;
}
